#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = -Iinclude -Iinclude\SDL2
CFLAGS = -Wall -fexceptions -std=c++11
RESINC = 
LIBDIR = -Llib
LIB = 
LDFLAGS = -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer

INC_DEBUG = $(INC) -Iinclude -Iinclude\SDL2
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR) -Llib
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS) -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\ZeroTempo.exe

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\ZeroTempo.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\src\\ActionSprite.o $(OBJDIR_DEBUG)\\src\\CastingBar.o $(OBJDIR_DEBUG)\\src\\Character.o $(OBJDIR_DEBUG)\\src\\Creature.o $(OBJDIR_DEBUG)\\src\\Helper.o $(OBJDIR_DEBUG)\\src\\MainWindow.o $(OBJDIR_DEBUG)\\src\\Map.o $(OBJDIR_DEBUG)\\src\\Menu.o $(OBJDIR_DEBUG)\\src\\Monster.o $(OBJDIR_DEBUG)\\src\\Move.o $(OBJDIR_DEBUG)\\src\\PartyStatusBox.o $(OBJDIR_DEBUG)\\src\\Skill.o $(OBJDIR_DEBUG)\\src\\SkillCastedBanner.o $(OBJDIR_DEBUG)\\src\\Sprite.o $(OBJDIR_DEBUG)\\src\\StatusAilments.o $(OBJDIR_DEBUG)\\src\\StatusBuff.o $(OBJDIR_DEBUG)\\src\\TargetSelection.o $(OBJDIR_DEBUG)\\src\\ZeroTempo_main.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\src\\ActionSprite.o $(OBJDIR_RELEASE)\\src\\CastingBar.o $(OBJDIR_RELEASE)\\src\\Character.o $(OBJDIR_RELEASE)\\src\\Creature.o $(OBJDIR_RELEASE)\\src\\Helper.o $(OBJDIR_RELEASE)\\src\\MainWindow.o $(OBJDIR_RELEASE)\\src\\Map.o $(OBJDIR_RELEASE)\\src\\Menu.o $(OBJDIR_RELEASE)\\src\\Monster.o $(OBJDIR_RELEASE)\\src\\Move.o $(OBJDIR_RELEASE)\\src\\PartyStatusBox.o $(OBJDIR_RELEASE)\\src\\Skill.o $(OBJDIR_RELEASE)\\src\\SkillCastedBanner.o $(OBJDIR_RELEASE)\\src\\Sprite.o $(OBJDIR_RELEASE)\\src\\StatusAilments.o $(OBJDIR_RELEASE)\\src\\StatusBuff.o $(OBJDIR_RELEASE)\\src\\TargetSelection.o $(OBJDIR_RELEASE)\\src\\ZeroTempo_main.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG)\\src md $(OBJDIR_DEBUG)\\src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\src\\ActionSprite.o: src\\ActionSprite.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\ActionSprite.cpp -o $(OBJDIR_DEBUG)\\src\\ActionSprite.o

$(OBJDIR_DEBUG)\\src\\CastingBar.o: src\\CastingBar.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\CastingBar.cpp -o $(OBJDIR_DEBUG)\\src\\CastingBar.o

$(OBJDIR_DEBUG)\\src\\Character.o: src\\Character.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Character.cpp -o $(OBJDIR_DEBUG)\\src\\Character.o

$(OBJDIR_DEBUG)\\src\\Creature.o: src\\Creature.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Creature.cpp -o $(OBJDIR_DEBUG)\\src\\Creature.o

$(OBJDIR_DEBUG)\\src\\Helper.o: src\\Helper.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Helper.cpp -o $(OBJDIR_DEBUG)\\src\\Helper.o

$(OBJDIR_DEBUG)\\src\\MainWindow.o: src\\MainWindow.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\MainWindow.cpp -o $(OBJDIR_DEBUG)\\src\\MainWindow.o

$(OBJDIR_DEBUG)\\src\\Map.o: src\\Map.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Map.cpp -o $(OBJDIR_DEBUG)\\src\\Map.o

$(OBJDIR_DEBUG)\\src\\Menu.o: src\\Menu.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Menu.cpp -o $(OBJDIR_DEBUG)\\src\\Menu.o

$(OBJDIR_DEBUG)\\src\\Monster.o: src\\Monster.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Monster.cpp -o $(OBJDIR_DEBUG)\\src\\Monster.o

$(OBJDIR_DEBUG)\\src\\Move.o: src\\Move.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Move.cpp -o $(OBJDIR_DEBUG)\\src\\Move.o

$(OBJDIR_DEBUG)\\src\\PartyStatusBox.o: src\\PartyStatusBox.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\PartyStatusBox.cpp -o $(OBJDIR_DEBUG)\\src\\PartyStatusBox.o

$(OBJDIR_DEBUG)\\src\\Skill.o: src\\Skill.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Skill.cpp -o $(OBJDIR_DEBUG)\\src\\Skill.o

$(OBJDIR_DEBUG)\\src\\SkillCastedBanner.o: src\\SkillCastedBanner.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\SkillCastedBanner.cpp -o $(OBJDIR_DEBUG)\\src\\SkillCastedBanner.o

$(OBJDIR_DEBUG)\\src\\Sprite.o: src\\Sprite.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Sprite.cpp -o $(OBJDIR_DEBUG)\\src\\Sprite.o

$(OBJDIR_DEBUG)\\src\\StatusAilments.o: src\\StatusAilments.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\StatusAilments.cpp -o $(OBJDIR_DEBUG)\\src\\StatusAilments.o

$(OBJDIR_DEBUG)\\src\\StatusBuff.o: src\\StatusBuff.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\StatusBuff.cpp -o $(OBJDIR_DEBUG)\\src\\StatusBuff.o

$(OBJDIR_DEBUG)\\src\\TargetSelection.o: src\\TargetSelection.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\TargetSelection.cpp -o $(OBJDIR_DEBUG)\\src\\TargetSelection.o

$(OBJDIR_DEBUG)\\src\\ZeroTempo_main.o: src\\ZeroTempo_main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\ZeroTempo_main.cpp -o $(OBJDIR_DEBUG)\\src\\ZeroTempo_main.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)\\src

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE)\\src md $(OBJDIR_RELEASE)\\src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\src\\ActionSprite.o: src\\ActionSprite.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\ActionSprite.cpp -o $(OBJDIR_RELEASE)\\src\\ActionSprite.o

$(OBJDIR_RELEASE)\\src\\CastingBar.o: src\\CastingBar.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\CastingBar.cpp -o $(OBJDIR_RELEASE)\\src\\CastingBar.o

$(OBJDIR_RELEASE)\\src\\Character.o: src\\Character.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Character.cpp -o $(OBJDIR_RELEASE)\\src\\Character.o

$(OBJDIR_RELEASE)\\src\\Creature.o: src\\Creature.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Creature.cpp -o $(OBJDIR_RELEASE)\\src\\Creature.o

$(OBJDIR_RELEASE)\\src\\Helper.o: src\\Helper.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Helper.cpp -o $(OBJDIR_RELEASE)\\src\\Helper.o

$(OBJDIR_RELEASE)\\src\\MainWindow.o: src\\MainWindow.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\MainWindow.cpp -o $(OBJDIR_RELEASE)\\src\\MainWindow.o

$(OBJDIR_RELEASE)\\src\\Map.o: src\\Map.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Map.cpp -o $(OBJDIR_RELEASE)\\src\\Map.o

$(OBJDIR_RELEASE)\\src\\Menu.o: src\\Menu.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Menu.cpp -o $(OBJDIR_RELEASE)\\src\\Menu.o

$(OBJDIR_RELEASE)\\src\\Monster.o: src\\Monster.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Monster.cpp -o $(OBJDIR_RELEASE)\\src\\Monster.o

$(OBJDIR_RELEASE)\\src\\Move.o: src\\Move.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Move.cpp -o $(OBJDIR_RELEASE)\\src\\Move.o

$(OBJDIR_RELEASE)\\src\\PartyStatusBox.o: src\\PartyStatusBox.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\PartyStatusBox.cpp -o $(OBJDIR_RELEASE)\\src\\PartyStatusBox.o

$(OBJDIR_RELEASE)\\src\\Skill.o: src\\Skill.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Skill.cpp -o $(OBJDIR_RELEASE)\\src\\Skill.o

$(OBJDIR_RELEASE)\\src\\SkillCastedBanner.o: src\\SkillCastedBanner.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\SkillCastedBanner.cpp -o $(OBJDIR_RELEASE)\\src\\SkillCastedBanner.o

$(OBJDIR_RELEASE)\\src\\Sprite.o: src\\Sprite.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Sprite.cpp -o $(OBJDIR_RELEASE)\\src\\Sprite.o

$(OBJDIR_RELEASE)\\src\\StatusAilments.o: src\\StatusAilments.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\StatusAilments.cpp -o $(OBJDIR_RELEASE)\\src\\StatusAilments.o

$(OBJDIR_RELEASE)\\src\\StatusBuff.o: src\\StatusBuff.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\StatusBuff.cpp -o $(OBJDIR_RELEASE)\\src\\StatusBuff.o

$(OBJDIR_RELEASE)\\src\\TargetSelection.o: src\\TargetSelection.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\TargetSelection.cpp -o $(OBJDIR_RELEASE)\\src\\TargetSelection.o

$(OBJDIR_RELEASE)\\src\\ZeroTempo_main.o: src\\ZeroTempo_main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\ZeroTempo_main.cpp -o $(OBJDIR_RELEASE)\\src\\ZeroTempo_main.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)\\src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

